version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: node --version
            - run: npm install
            - run: NODE_OPTIONS=--max_old_space_size=4096  npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test

